# -*- coding: utf-8 -*-
"""preprocessing

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XwECwJGr9HEY_p4CMGnp7zKmciIRN5TC
"""

import pandas as pd

df = pd.read_csv("/content/ai_job_trends_dataset.csv")
df.drop_duplicates(inplace=True)
df.fillna(df.median(numeric_only=True), inplace=True)
df.to_csv("/content/cleaned_data.csv", index=False)

print(df.info())
print(df.describe())
