# -*- coding: utf-8 -*-
"""validation

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XwECwJGr9HEY_p4CMGnp7zKmciIRN5TC
"""

import pandas as pd
import joblib

from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

from sklearn.model_selection import train_test_split

df = pd.read_csv("cleaned_data.csv"
)

target = "Projected Openings (2030)"

X = df.drop(
    columns=[target]
)

y = df[target]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

model = joblib.load(
    "../models/linear_regression.pkl"
)

pred = model.predict(X_test)

validation = pd.DataFrame({
    "Metric":[
        "MAE",
        "RMSE",
        "R2"
    ],
    "Value":[
        mean_absolute_error(
            y_test,
            pred
        ),
        mean_squared_error(
            y_test,
            pred
        ) ** 0.5,
        r2_score(
            y_test,
            pred
        )
    ]
})

validation.to_csv(
    "../reports/validation_metrics.csv",
    index=False
)

print(validation)